### ISSUE TITLE
Can't sign in with facebook / choose "not now"

### ISSUE THREAD

**Issue by cherry-wave** [adrielcafe/NMSAlphabetAndroidApp#4]
I get nearly the same error (just different lines of course)

Facebook sign in:

```
05-02 20:16:20.418 32146-32187/cafe.adriel.nmsalphabet.free E/CustomActivityOnCrash: App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
                                                                                     java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
                                                                                         at android.os.Handler.<init>(Handler.java:200)
                                                                                         at android.os.Handler.<init>(Handler.java:114)
                                                                                         at android.widget.Toast$TN.<init>(Toast.java:345)
                                                                                         at android.widget.Toast.<init>(Toast.java:101)
                                                                                         at android.widget.Toast.makeText(Toast.java:259)
                                                                                         at android.widget.Toast.makeText(Toast.java:286)
                                                                                         at cafe.adriel.nmsalphabet.util.Util.isConnected(Util.java:166)
                                                                                         at cafe.adriel.nmsalphabet.ui.SplashActivity.facebookSignIn(SplashActivity.java:108)
                                                                                         at cafe.adriel.nmsalphabet.ui.SplashActivity.access$100(SplashActivity.java:34)
                                                                                         at cafe.adriel.nmsalphabet.ui.SplashActivity$1$1.run(SplashActivity.java:79)
                                                                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                         at java.lang.Thread.run(Thread.java:818)
```

Anonymous sign in:

```
05-02 20:15:57.782 29895-29952/cafe.adriel.nmsalphabet.free E/CustomActivityOnCrash: App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
                                                                                     java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
                                                                                         at android.os.Handler.<init>(Handler.java:200)
                                                                                         at android.os.Handler.<init>(Handler.java:114)
                                                                                         at android.widget.Toast$TN.<init>(Toast.java:345)
                                                                                         at android.widget.Toast.<init>(Toast.java:101)
                                                                                         at android.widget.Toast.makeText(Toast.java:259)
                                                                                         at android.widget.Toast.makeText(Toast.java:286)
                                                                                         at cafe.adriel.nmsalphabet.util.Util.isConnected(Util.java:166)
                                                                                         at cafe.adriel.nmsalphabet.ui.SplashActivity.anonymousSignIn(SplashActivity.java:140)
                                                                                         at cafe.adriel.nmsalphabet.ui.SplashActivity.access$200(SplashActivity.java:34)
                                                                                         at cafe.adriel.nmsalphabet.ui.SplashActivity$2$1.run(SplashActivity.java:91)
                                                                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                         at java.lang.Thread.run(Thread.java:818)
```

**Comment by adrielcafe** [comment]
Fixed.
I had tried to show a Toast outside UI thread, just put it on Activity.runOnUiThread() to fix

**Comment by cherry-wave** [comment]
Yeah I guessed that ;) Great. Will test everything this afternoon again!
