### ISSUE TITLE
Error when adding new word in profile-tab

### ISSUE THREAD

**Issue by cherry-wave** [adrielcafe/NMSAlphabetAndroidApp#7]
When adding my first word (no words previously added) this error came and the screen didn't update:

```
05-28 14:40:57.583 27597-27597/cafe.adriel.nmsalphabet.free E/EventBus: Could not dispatch event: class cafe.adriel.nmsalphabet.event.TranslationUpdatedEvent to subscribing class class cafe.adriel.nmsalphabet.ui.WordsFragment
                                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'void cafe.adriel.nmsalphabet.ui.adapter.ProfileAdapter.updateWordAndTranslations(cafe.adriel.nmsalphabet.model.AlienWord, java.util.List)' on a null object reference
                                                                            at cafe.adriel.nmsalphabet.ui.WordsFragment.onEvent(WordsFragment.java:143)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
                                                                            at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:416)
                                                                            at org.greenrobot.eventbus.EventBus.checkPostStickyEventToSubscription(EventBus.java:199)
                                                                            at org.greenrobot.eventbus.EventBus.subscribe(EventBus.java:185)
                                                                            at org.greenrobot.eventbus.EventBus.register(EventBus.java:139)
                                                                            at cafe.adriel.nmsalphabet.ui.WordsFragment.onStart(WordsFragment.java:130)
                                                                            at android.support.v4.app.Fragment.performStart(Fragment.java:2000)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1102)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
                                                                            at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2051)
                                                                            at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:185)
                                                                            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                                                                            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
                                                                            at android.app.Activity.performStart(Activity.java:6268)
                                                                            at android.app.Activity.performRestart(Activity.java:6314)
                                                                            at android.app.Activity.performResume(Activity.java:6319)
                                                                            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
                                                                            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1388)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

When I clicked on update, the new word appeared. I added another word and there was no longer an error, but the word didn't appear again.

**Comment by adrielcafe** [comment]
Fixed.
Thanks!
